from __future__ import annotations

USERS = {
    "U001": {
        "user_id": "U001",
        "name": "测试员工",
        "company_id": "C001",
        "dept_id": "D001",
        "role": "employee",
        "manager_id": "U002",
    }
}


APPROVAL_TEMPLATES = {
    "leave": {
        "template_id": "tpl_leave_001",
        "approval_type": "leave",
        "title": "请假申请",
        "category": "人事",
        "group_name": "行政",
        "aliases": ["测试请假", "审批编辑-请假控件组"],
        "intent_keywords": ["请假", "休假", "年假", "事假", "病假", "调休"],
        "visibility": "all",
        "enabled": True,
        "is_common": True,
        "sort_order": 10,
        "fields": [
            {
                "name": "leave_type",
                "label": "请假类型",
                "type": "enum",
                "required": True,
                "options": ["年假", "事假", "病假", "调休"],
                "aliases": ["假种", "假期类型"],
                "extract_patterns": [],
                "question": "请先选择请假类型：年假、事假、病假、调休。",
            },
            {
                "name": "start_date",
                "label": "开始时间",
                "type": "date",
                "required": True,
                "options": [],
                "aliases": ["开始", "从", "起始时间"],
                "extract_patterns": [
                    r"(?:从|开始时间是?)(\d{4}[-/.年]\d{1,2}[-/.月]\d{1,2}日?)"
                ],
                "question": "请告诉我请假的开始时间，例如 2026-06-01。",
            },
            {
                "name": "end_date",
                "label": "结束时间",
                "type": "date",
                "required": True,
                "options": [],
                "aliases": ["结束", "到", "截止时间"],
                "extract_patterns": [
                    r"(?:到|至|结束时间是?)(\d{4}[-/.年]\d{1,2}[-/.月]\d{1,2}日?)"
                ],
                "question": "请告诉我请假的结束时间，例如 2026-06-03。",
            },
            {
                "name": "reason",
                "label": "请假原因",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["原因", "理由"],
                "extract_patterns": [r"(?:因为|原因是|理由是)(.+)$"],
                "question": "请补充请假原因。",
            },
        ],
    },
    "expense": {
        "template_id": "tpl_expense_001",
        "approval_type": "expense",
        "title": "报销申请",
        "category": "财务",
        "group_name": "zh-测试",
        "aliases": ["测试报销", "审批编辑-报销控件组"],
        "intent_keywords": [
            "报销",
            "发票",
            "差旅费",
            "餐饮费",
            "办公用品",
            "交通费",
            "住宿费",
        ],
        "visibility": "all",
        "enabled": True,
        "is_common": True,
        "sort_order": 20,
        "fields": [
            {
                "name": "expense_type",
                "label": "报销类型",
                "type": "enum",
                "required": True,
                "options": ["差旅费", "餐饮费", "办公用品", "交通费", "住宿费"],
                "aliases": ["费用类型", "报销类别"],
                "extract_patterns": [],
                "question": "请告诉我报销类型，例如差旅费、餐饮费、办公用品。",
            },
            {
                "name": "amount",
                "label": "金额",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["金额", "费用", "报销金额"],
                "extract_patterns": [r"(?:金额|费用|报销)\D*(\d+(?:\.\d+)?)"],
                "question": "请告诉我报销金额，例如 3200。",
            },
            {
                "name": "reason",
                "label": "报销事由",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["事由", "原因", "用途"],
                "extract_patterns": [
                    r"(?:事由是|原因是|用途是|因为)(.+?)(?:，?发票|$)",
                    r"\d+(?:\.\d+)?\s*元[，, ]*(.+?)(?:，?发票|$)",
                ],
                "question": "请补充报销事由。",
            },
            {
                "name": "invoice",
                "label": "发票情况",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["发票", "票据"],
                "extract_patterns": [r"(发票(?:已提供|待补充|后补|无|没有|有)?)"],
                "question": "请说明发票情况，例如已提供、待补充、无发票。",
            },
        ],
    },
    "purchase": {
        "template_id": "tpl_purchase_001",
        "approval_type": "purchase",
        "title": "采购申请",
        "category": "行政",
        "group_name": "常用审批",
        "aliases": ["采购申请2", "基础控件", "采购"],
        "intent_keywords": ["采购", "购买", "购置", "买"],
        "visibility": "all",
        "enabled": True,
        "is_common": True,
        "sort_order": 30,
        "fields": [
            {
                "name": "item",
                "label": "采购物品",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["物品", "采购物", "商品"],
                "extract_patterns": [
                    r"(?:采购|购买|购置|买)([\u4e00-\u9fa5A-Za-z0-9]+)"
                ],
                "question": "请告诉我采购物品名称。",
            },
            {
                "name": "quantity",
                "label": "数量",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["数量"],
                "extract_patterns": [r"(\d+(?:\.\d+)?)\s*(?:台|个|件|套)"],
                "question": "请告诉我采购数量。",
            },
            {
                "name": "budget",
                "label": "预算",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["预算", "金额", "费用"],
                "extract_patterns": [r"(?:预算|金额|费用)\D*(\d+(?:\.\d+)?)"],
                "question": "请告诉我采购预算，例如 12000。",
            },
            {
                "name": "purpose",
                "label": "采购用途",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["用途", "原因", "目的"],
                "extract_patterns": [r"(?:用途是|原因是|目的是|因为)(.+)$"],
                "question": "请说明采购用途。",
            },
        ],
    },
    "seal": {
        "template_id": "tpl_seal_001",
        "approval_type": "seal",
        "title": "用章申请",
        "category": "行政",
        "group_name": "系统审批",
        "aliases": ["盖章", "合同章申请", "公章申请"],
        "intent_keywords": ["用章", "盖章", "公章", "合同章"],
        "visibility": "all",
        "enabled": True,
        "is_common": False,
        "sort_order": 40,
        "fields": [
            {
                "name": "seal_type",
                "label": "印章类型",
                "type": "enum",
                "required": True,
                "options": ["公章", "合同章", "财务章"],
                "aliases": ["章类型", "印章"],
                "extract_patterns": [],
                "question": "请说明要使用的印章类型：公章、合同章、财务章。",
            },
            {
                "name": "document_name",
                "label": "文件名称",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["文件", "材料", "合同"],
                "extract_patterns": [
                    r"(?:文件|材料|合同)(?:名称)?是?([\u4e00-\u9fa5A-Za-z0-9《》_-]+)"
                ],
                "question": "请告诉我需要盖章的文件名称。",
            },
            {
                "name": "copies",
                "label": "份数",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["份数", "几份"],
                "extract_patterns": [r"(\d+(?:\.\d+)?)\s*份"],
                "question": "请告诉我盖章份数。",
            },
            {
                "name": "purpose",
                "label": "用章用途",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["用途", "原因"],
                "extract_patterns": [r"(?:用途是|原因是|因为)(.+)$"],
                "question": "请说明用章用途。",
            },
        ],
    },
    "outbound": {
        "template_id": "tpl_outbound_001",
        "approval_type": "outbound",
        "title": "测试出库",
        "category": "库存管理",
        "group_name": "zh-测试",
        "aliases": ["仅出库", "审批编辑-仅出库"],
        "intent_keywords": ["出库", "领料", "发货", "库存"],
        "visibility": "all",
        "enabled": True,
        "is_common": False,
        "sort_order": 50,
        "fields": [
            {
                "name": "warehouse",
                "label": "出库仓库",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["仓库", "库房"],
                "extract_patterns": [r"(?:仓库|库房)是?([\u4e00-\u9fa5A-Za-z0-9_-]+)"],
                "question": "请告诉我出库仓库。",
            },
            {
                "name": "item",
                "label": "出库物品",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["物品", "商品", "物料"],
                "extract_patterns": [
                    r"(?:出库|领用|领料)([\u4e00-\u9fa5A-Za-z0-9_-]+)"
                ],
                "question": "请告诉我出库物品。",
            },
            {
                "name": "quantity",
                "label": "数量",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["数量"],
                "extract_patterns": [r"(\d+(?:\.\d+)?)\s*(?:个|件|箱|套)"],
                "question": "请告诉我出库数量。",
            },
            {
                "name": "reason",
                "label": "出库原因",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["原因", "用途"],
                "extract_patterns": [r"(?:原因是|用途是|因为)(.+)$"],
                "question": "请说明出库原因。",
            },
        ],
    },
    "inbound": {
        "template_id": "tpl_inbound_001",
        "approval_type": "inbound",
        "title": "测试入库",
        "category": "库存管理",
        "group_name": "zh-测试",
        "aliases": ["仅入库", "审批编辑-仅入库"],
        "intent_keywords": ["入库", "收货", "到货", "库存"],
        "visibility": "all",
        "enabled": True,
        "is_common": False,
        "sort_order": 60,
        "fields": [
            {
                "name": "warehouse",
                "label": "入库仓库",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["仓库", "库房"],
                "extract_patterns": [r"(?:仓库|库房)是?([\u4e00-\u9fa5A-Za-z0-9_-]+)"],
                "question": "请告诉我入库仓库。",
            },
            {
                "name": "item",
                "label": "入库物品",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["物品", "商品", "物料"],
                "extract_patterns": [r"(?:入库|收货)([\u4e00-\u9fa5A-Za-z0-9_-]+)"],
                "question": "请告诉我入库物品。",
            },
            {
                "name": "quantity",
                "label": "数量",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["数量"],
                "extract_patterns": [r"(\d+(?:\.\d+)?)\s*(?:个|件|箱|套)"],
                "question": "请告诉我入库数量。",
            },
        ],
    },
    "overtime": {
        "template_id": "tpl_overtime_001",
        "approval_type": "overtime",
        "title": "测试加班",
        "category": "行政",
        "group_name": "zh-测试",
        "aliases": ["加班控件组", "审批编辑-加班控件组"],
        "intent_keywords": ["加班", "延时工作"],
        "visibility": "all",
        "enabled": True,
        "is_common": False,
        "sort_order": 70,
        "fields": [
            {
                "name": "start_date",
                "label": "加班开始时间",
                "type": "date",
                "required": True,
                "options": [],
                "aliases": ["开始", "从"],
                "extract_patterns": [
                    r"(?:从|开始时间是?)(\d{4}[-/.年]\d{1,2}[-/.月]\d{1,2}日?)"
                ],
                "question": "请告诉我加班开始时间，例如 2026-06-01。",
            },
            {
                "name": "hours",
                "label": "加班时长",
                "type": "number",
                "required": True,
                "options": [],
                "aliases": ["时长", "小时"],
                "extract_patterns": [r"(\d+(?:\.\d+)?)\s*(?:小时|h)"],
                "question": "请告诉我加班时长，例如 2 小时。",
            },
            {
                "name": "reason",
                "label": "加班原因",
                "type": "text",
                "required": True,
                "options": [],
                "aliases": ["原因", "理由"],
                "extract_patterns": [r"(?:原因是|因为)(.+)$"],
                "question": "请说明加班原因。",
            },
        ],
    },
}
